const INSTAGRAM_USERNAME="";
const plans={
esencial:{tag:"Web Esencial · Desde 249 €",name:"Web Esencial",title:"La web que hace que tu negocio parezca tan profesional como es.",copy:"Pensada para negocios que necesitan una presencia clara, cuidada y fácil de entender. El objetivo no es llenar la pantalla de cosas: es que quien entre sepa quién eres, qué haces y cómo contactarte.",demo:"Ejemplo: barbería, clínica, profesional independiente, pequeño negocio local o servicio.",demoUrl:"demos/esencial.html",preview:"essential",items:["Diseño adaptado a tu marca","Inicio comercial y presentación","Servicios o carta visual","Contacto, ubicación y redes","Diseño responsive móvil","Preparada para publicar"]},
profesional:{tag:"Web Profesional · Desde 449 €",name:"Web Profesional",title:"Más contenido. Más confianza. Más motivos para elegirte.",copy:"Para empresas que necesitan explicar mejor su propuesta y cuidar cada parte del recorrido del cliente. Añadimos secciones, movimiento visual y recursos que ayudan a presentar el negocio con más fuerza.",demo:"Ejemplo: restaurante, gimnasio, club, academia, empresa de servicios o marca personal avanzada.",demoUrl:"demos/profesional.html",preview:"professional",items:["Todo lo incluido en Esencial","Secciones y páginas adicionales","Animaciones y microinteracciones","Galerías y formularios","Casos, proyectos o portfolio","Estructura orientada a conversión"]},
tienda:{tag:"Tienda Online · Desde 649 €",name:"Tienda Online",title:"Tu escaparate abierto todos los días, a cualquier hora.",copy:"Diseñamos una experiencia de compra coherente con tu marca para que el producto sea el protagonista y comprar resulte sencillo.",demo:"Ejemplo: ropa, complementos, coleccionismo, merchandising o productos propios.",demoUrl:"demos/tienda.html",preview:"shop",items:["Diseño de tienda personalizado","Catálogo y fichas de producto","Carrito y proceso de compra","Gestión de pedidos","Filtros y colecciones","Funciones extra según catálogo"]},
avanzada:{tag:"Web Avanzada · Desde 899 €",name:"Web Avanzada",title:"Cuando una web ya tiene que hacer cosas por ti.",copy:"Para proyectos que necesitan cuentas de usuario, zonas privadas, automatizaciones, datos o comportamientos específicos.",demo:"Ejemplo: portal de clientes, área privada de socios, reservas complejas, paneles o herramientas online.",demoUrl:"demos/avanzada.html",preview:"dashboard",items:["Registro e inicio de sesión","Perfiles y zonas privadas","Paneles personalizados","Automatizaciones","Base de datos e integraciones","Lógica específica del negocio"]},
especial:{tag:"Proyecto Especial · Presupuesto personalizado",name:"Proyecto Especial",title:"Si tu idea no cabe en una plantilla, mejor.",copy:"Aquí entran las plataformas y experiencias online que requieren plantear arquitectura, usuarios, reglas y funciones desde cero. El precio depende de todo lo que tenga que hacer el sistema.",demo:"Ejemplo: comunidad con perfiles y chat, plataforma de compraventa, subastas, rifas, marketplace o juego online sencillo.",demoUrl:"demos/especial.html",preview:"community",items:["Usuarios, perfiles y roles","Chat e interacción entre usuarios","Tiendas y marketplaces","Subastas, rifas y sistemas propios","Juegos sencillos online","Panel de administración y moderación"]}
};
const modal=document.querySelector("#planModal"),content=document.querySelector("#modalContent"),toast=document.querySelector("#toast");
function showToast(msg){toast.textContent=msg;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),3200)}
function preview(type){
 if(type==="essential")return `<div class="visual-preview"><div class="visual-browser"><i></i><i></i><i></i></div><div class="visual-stage"><div class="visual-nav"><strong>BARBERÍA NORTE</strong><span>Inicio · Servicios · Contacto</span></div><div class="visual-hero"><div class="visual-copy"><small>BARBERÍA · CÓRDOBA</small><h4>Tu estilo empieza aquí.</h4><p>Una portada clara, servicios principales y un botón directo a reserva o contacto.</p><span class="visual-cta">Reservar cita</span></div><div class="visual-art">IMAGEN PRINCIPAL</div></div><div class="visual-cards"><div class="visual-card"><b>Corte</b><span>Servicio destacado</span></div><div class="visual-card"><b>Barba</b><span>Segundo servicio</span></div><div class="visual-card"><b>Horario</b><span>Información rápida</span></div></div></div></div><p class="preview-caption">Así se vería una Web Esencial: directa, limpia y suficiente para presentar un negocio, sus servicios y cómo contactar.</p>`;
 if(type==="professional")return `<div class="visual-preview"><div class="visual-browser"><i></i><i></i><i></i></div><div class="visual-stage" style="background:#111;color:#fff"><div class="visual-nav" style="background:#171717;color:#fff"><strong>ORIGEN FITNESS</strong><span>Entrena · Equipo · Tarifas · Contacto</span></div><div class="visual-hero" style="background:#1a1a1a"><div class="visual-copy"><small style="color:#9ee0b6">ENTRENA DIFERENTE</small><h4>Construye tu mejor versión.</h4><p style="color:#b9c0bb">Más secciones, mensajes comerciales, llamadas a la acción, galería y una imagen más potente.</p><span class="visual-cta" style="background:#fff;color:#111">Ver planes</span></div><div class="visual-art" style="background:linear-gradient(135deg,#36483d,#111)">VIDEO / GALERÍA</div></div><div class="visual-cards"><div class="visual-card"><b>Entrenamiento</b><span>Servicio explicado</span></div><div class="visual-card"><b>Equipo</b><span>Confianza y marca</span></div><div class="visual-card"><b>Resultados</b><span>Casos y testimonios</span></div></div></div></div><p class="preview-caption">Una Web Profesional permite contar mejor la historia del negocio, mostrar más contenido y trabajar mucho más la conversión.</p>`;
 if(type==="shop")return `<div class="visual-preview"><div class="visual-browser"><i></i><i></i><i></i></div><div class="visual-stage"><div class="visual-nav"><strong>NØRVA</strong><span>Novedades · Hombre · Mujer · Carrito (2)</span></div><h4 style="font-size:24px;margin:15px 0">Nueva colección</h4><div class="visual-store"><div class="visual-product"><div class="thumb"></div><b>Essential Tee · 29,90 €</b></div><div class="visual-product"><div class="thumb"></div><b>Studio Hoodie · 59,90 €</b></div><div class="visual-product"><div class="thumb"></div><b>Core Cap · 24,90 €</b></div></div></div></div><p class="preview-caption">En una Tienda Online entran catálogo, fichas de producto, carrito, pagos, pedidos y filtros según lo que venda el cliente.</p>`;
 if(type==="dashboard")return `<div class="visual-preview"><div class="visual-browser"><i></i><i></i><i></i></div><div class="visual-stage"><div class="visual-dashboard"><div class="visual-side"><b>CLUB+</b><p>Inicio</p><p>Reservas</p><p>Mi perfil</p><p>Mensajes</p></div><div class="visual-main"><h4 style="margin:0 0 12px">Hola, Andrea 👋</h4><div class="visual-stats"><div class="visual-stat"><small>PRÓXIMA RESERVA</small><b>Viernes · 18:30</b></div><div class="visual-stat"><small>SESIONES</small><b>12 este mes</b></div><div class="visual-stat"><small>PLAN</small><b>Premium</b></div></div><div class="visual-card" style="margin-top:10px"><b>Actividad reciente</b><span>Reservas, datos, avisos y acciones privadas del usuario.</span></div></div></div></div></div><p class="preview-caption">Una Web Avanzada ya trabaja con usuarios, áreas privadas, datos, automatizaciones y funciones personalizadas.</p>`;
 return `<div class="visual-preview"><div class="visual-browser"><i></i><i></i><i></i></div><div class="visual-stage"><div class="visual-nav"><strong>COLLECT HUB</strong><span>Comunidad · Mercado · Subastas · Perfil</span></div><div class="visual-community"><div><b>Comunidades</b><p>Cartas</p><p>Gaming</p><p>Intercambios</p></div><div class="visual-feed"><div class="visual-post"><b>@alexcollector</b><p>¿Qué os parece esta nueva adquisición?</p></div><div class="visual-post"><b>@marta.cards</b><p>Subasta abierta hasta las 22:00.</p></div><div class="visual-post"><b>@retroclub</b><p>Nueva rifa disponible.</p></div></div><div><b>En directo</b><p>🟢 128 usuarios online</p><p>🔥 6 subastas</p><p>🎟️ 3 rifas</p></div></div></div></div><p class="preview-caption">Un Proyecto Especial puede combinar comunidad, perfiles, chats, subastas, rifas, tienda, roles, moderación y otras reglas propias.</p>`;
}
async function contactPlan(key){const p=plans[key];const message=`Hola, he visto vuestra web de SoroByte y me interesa el plan "${p.name}". Me gustaría contaros mi idea y pedir presupuesto.`;try{await navigator.clipboard.writeText(message)}catch(e){}if(INSTAGRAM_USERNAME){window.open(`https://ig.me/m/${INSTAGRAM_USERNAME}`,"_blank");showToast("Mensaje copiado. Pégalo en el DM y envíalo.");}else{showToast(`Mensaje de "${p.name}" copiado. El DM se activará cuando añadamos el Instagram definitivo.`);}}
document.querySelectorAll(".contact-plan").forEach(btn=>btn.addEventListener("click",()=>contactPlan(btn.dataset.plan)));
document.querySelectorAll(".open-detail").forEach(btn=>btn.addEventListener("click",()=>{const key=btn.dataset.plan,p=plans[key];content.innerHTML=`<span class="modal-sub">${p.tag}</span><h2 class="modal-title">${p.title}</h2><p class="modal-copy">${p.copy}</p>${preview(p.preview)}<h3>Qué incluye este nivel</h3><div class="modal-grid">${p.items.map(i=>`<div class="modal-chip">✓ ${i}</div>`).join("")}</div><div class="modal-actions"><a class="btn btn-ghost" href="${p.demoUrl}?v=4" target="_blank">Entrar en la demo</a><button class="btn modal-contact" data-plan="${key}">Quiero este plan</button></div><p class="modal-copy" style="margin-top:24px">La demo es solo un ejemplo visual. La web final se diseña a medida con la identidad, colores y necesidades de cada negocio.</p>`;content.querySelector(".modal-contact").addEventListener("click",()=>contactPlan(key));modal.classList.add("active");modal.setAttribute("aria-hidden","false");}));
function closeModal(){modal.classList.remove("active");modal.setAttribute("aria-hidden","true")}
document.querySelector(".modal-close").addEventListener("click",closeModal);
document.querySelector(".modal-backdrop").addEventListener("click",closeModal);
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
const glow=document.querySelector(".cursor-glow");if(glow){document.addEventListener("mousemove",e=>{glow.style.cssText=`position:fixed;left:${e.clientX-180}px;top:${e.clientY-180}px;width:360px;height:360px;border-radius:50%;background:radial-gradient(circle,rgba(53,242,127,.055),transparent 65%);pointer-events:none;z-index:-1`})}